### ISSUE TITLE
Add support for setting middle C

### ISSUE THREAD

**Issue by walmik** [walmik/scribbletune#28]
Currently Scribbletune defaults to C4. This is fine but technically we must provide a way to change this. For instance most software DAWs such as Ableton Live and Propellehead Reason have C3 as the middle C. So users (including me) of these softwares have to manually transpose what comes from Scribbletune an octave up. We should allow users to set the middle C when they require or import Scribbletune or at least set it up right after they import.

**Comment by ddxtanx** [comment]
@walmik Is this now fixed as a result of #32 being merged?

**Comment by walmik** [comment]
Oh yes! And thank you once again for fixing this!
