### ISSUE TITLE
Create modes or scales with a single string arg

### ISSUE THREAD

**Issue by walmik** [walmik/scribbletune#29]
Currently a mode or a scale is created like this:
`var cMajorScale = scribble.scale('c', 'major');    // ['c3', 'd3', 'e3', 'f3', 'g3', 'a3', 'b3', 'c4']`

If you want it in a specific octave then,
`var cMajorScale4 = scribble.scale('c', 'major', 4);    // ['c4', 'd4', 'e4', 'f4', 'g4', 'a4', 'b4', 'c5']`

Make a provision to create the scale with a single string argument, like
`var cMajorScale = scribble.scale('c major');    // ['c3', 'd3', 'e3', 'f3', 'g3', 'a3', 'b3', 'c4']`

or,
`var cMajorScale4 = scribble.scale('c major 4');    // ['c4', 'd4', 'e4', 'f4', 'g4', 'a4', 'b4', 'c5']`

**Comment by Adam-Morris** [comment]
Going to attempt to add this feature, I'm a beginner at Javascript but it seems simple enough.

**Comment by Adam-Morris** [comment]
Added this feature with [this](https://github.com/walmik/scribbletune/pull/30) pull request.

**Comment by walmik** [comment]
Closing this issue as this feature is added in v0.10
Thank you @Adam-Morris! I m gonna present at ForwardJS tomorrow. I ll make it a point to mention your contribution.
