### ISSUE TITLE
Engine requirement when installing under yarn

### ISSUE THREAD

**Issue by robations** [walmik/scribbletune#33]
Getting this issue when trying to install with yarn (under node v6):

```
$ yarn add scribbletune
error scribbletune@0.9.1: The engine "node" is incompatible with this module. Expected version ">6.x.x".
```

I wonder if the spec would be better written `>=6` ?

**Comment by robations** [comment]
> Scribbletune (Requires Node 4+)

Just noticed this needs updating too (README.md).

**Comment by SolarKing** [comment]
Similar issue for me, I have `v6.9.1` of node installed:
```
$ node -v
v6.9.1
```

And running `yarn add scribbletune` prints out the following:

```
yarn add v0.23.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error scribbletune@0.9.1: The engine "node" is incompatible with this module. Expected version ">6.x.x".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by SolarKing** [comment]
As a workaround, I ran this to get scribbletune installed via `yarn`:

```
yarn add --ignore-engines scribbletune
```

Hope this helps for now, but yeah I think the spec would be better written as  `>=6.x.x` ?

**Comment by walmik** [comment]
Wow, I had no idea that was happening on yarn. I ve not yet started using yarn (I ll probably get around to it soon) but in the mean time, if you guys have some suggestions on how to fix this, or better still a PR that fixes this, then that ll be super awesome!

**Comment by walmik** [comment]
Fixed since `0.11.x` onward

**Comment by robations** [comment]
Cool. I take it that's not pushed to github yet. I see up to versions 0.9 and 1 alpha.

**Comment by walmik** [comment]
@robations good catch, looks like missed tagging v0.11.3 Just did it, thanks!
