### ISSUE TITLE
Install process issues

### ISSUE THREAD

**Issue by sarathysenthil** [walmik/scribbletune#38]
Hi,
I installed Node.js and npm files. Now how to install scribble tune and how to run it from the terminal.
can anyone help me..

**Comment by sarathysenthil** [comment]
I am getting this error but i am having the file 

![screen shot 2017-07-22 at 4 39 22 pm](https://user-images.githubusercontent.com/21057614/28490635-83552da0-6efc-11e7-8ce5-70012a5bdf36.png)

**Comment by MaximeMaillet** [comment]
Hi, can we have content of 1.js ?

**Comment by sarathysenthil** [comment]
const scribble = require('scribbletune');
let chords = scribble.clip({
    notes: ['F#min', 'C#min', 'Dmaj', 'Bmin', 'Emaj', 'Amaj', 'Dmaj', 'C#min', 'Amaj'],
    pattern: 'x_x_x_--'.repeat(8),
    sizzle: true
});  
 
scribble.midi(chords, 'chords.mid');

**Comment by walmik** [comment]
Hello there, first `cd` to the directory where you have the file named `1.js` and then run `node 1.js`.
