### ISSUE TITLE
Add half notes, quarter notes, etc...

### ISSUE THREAD

**Issue by ddxtanx** [walmik/scribbletune#42]
Looking at the README, I could not find any references to setting notes to different lengths. Is there currently a way to do this, or does this feature need to be added in?

**Comment by walmik** [comment]
The way to do that is a bit tricky. We do have a way out currently by a param called noteLength. So look at this default setting:
```
var clip = scribble.clip({
    notes: 'c4',
    pattern: 'x'.repeat(16)
});
```
As you can imagine, that ll through out a bar of sixteenth notes. To play thirtysecondth notes, we need to bump the HDR speed in the MIDI itself. In Scribbletune you can set the noteLength param for this:
```
var clip = scribble.clip({
    notes: 'c4',
    pattern: 'x'.repeat(32),
    noteLength: 1/32
});
```
This will subdivide the bar into 32 beats instead.

Another way of looking at it is, and coming back to the default example (where it 1/16 by default):
```
var clip = scribble.clip({
    notes: 'c4',
    pattern: 'x_'.repeat(8)
});
```

In ^ there I ve added an underscore to the x. This acts as a sustain of sorts. In this case it ll sustain it for twice an x. So `x_` acts as an eighth note. Similarly `x___` acts as a quarter note. The same can be done by messing with the noteLength as well:
```
var clip = scribble.clip({
    notes: 'c4',
    pattern: 'x'.repeat(4),
    noteLength: 1/4
});
```

Lemme know if that made sense :)

**Comment by ddxtanx** [comment]
@walmik Thank you for the explanation on the note length! That does make a lot of sense.
