### ISSUE TITLE
Allow for note to be both lower and UPPERCASE

### ISSUE THREAD

**Issue by highri5e** [walmik/scribbletune#49]
Probably not really an issue (I'm very very new to Git,Github) but...

scribble.clip() allows for notes to be written with lower case 'c4' and not 'C4'.
Is that by design ie. uppercase letters are for chords only?
Or would it be beneficial to allow both lower and upper in?
by modifying this:
```
	// Validate provided notes
	params.notes.forEach(el => {
		assert(el.match(/[abcdefg]#?[0-9]/g) !== null, el + ' is not a valid note!');
	});
```

To this:
```
	// Validate provided notes
	params.notes.forEach(el => {
		assert(el.match(/[a-gA-G]#?[0-9]/g) !== null, el + ' is not a valid note!');
	});
```
btw, I have worked on the simplistic UI for Scribbletune, find it here: [https://github.com/highri5e/ElectroScribble](https://github.com/highri5e/ElectroScribble)

**Comment by walmik** [comment]
Sorry for the delay on addressing this one. Uppercase note names are now allowed as of 0.11.1 Thank you for the suggestion @highri5e
