### ISSUE TITLE
using the library in the browser

### ISSUE THREAD

**Issue by enorrmann** [walmik/scribbletune#53]
for instance, to generate and render midis on the fly (using another lib)

**Comment by highri5e** [comment]
I've created a simple app in Electron, It's work in progress.
you can play instruments on the keyboard, capture the notes, generate and play midi.

You can check it out here: [https://github.com/highri5e/ElectroScribble](https://github.com/highri5e/ElectroScribble)

**Comment by enorrmann** [comment]
I will check that out ! thx @highri5e !

**Comment by walmik** [comment]
Here s another way I tried, where I used scribbletune in the browser to create an app: http://scribbletune.com/johann/#/piano

**Comment by walmik** [comment]
In other words it s possible to use Scribbletune in the browser. You can use webpack or browserify to get scribbletune to your clientside JS.

**Comment by enorrmann** [comment]
this is great ! exactly what I was looking for
