### ISSUE TITLE
Is it possible to add a sustain to some notes?

### ISSUE THREAD

**Issue by ProgrammingLife** [walmik/scribbletune#60]
Is it possible to add a sustain to some notes?

**Comment by walmik** [comment]
Yes a simple sustain can be obtained by using `_` (the underscore symbol), something like this:

```
var scribble = require('scribbletune');

var clip = scribble.clip({
	notes: 'c4 e4',
	pattern: 'xx______'
});

scribble.midi(clip);
```
This will sustain the e4 note:
<img width="483" alt="sustain" src="https://user-images.githubusercontent.com/467030/35782010-890f279c-09a6-11e8-846b-ce0ffeb12487.png">

**Comment by walmik** [comment]
@ProgrammingLife Lemme if that helps.
