### ISSUE TITLE
How to play two or more notes simultaneously?

### ISSUE THREAD

**Issue by ProgrammingLife** [walmik/scribbletune#62]
How to play two or more notes simultaneously without using a chords like C#min, Dmaj?

**Comment by walmik** [comment]
You can use an array for notes and pass another array for each step where you want the multiple notes:

```
var scribble = require('scribbletune');

var clip = scribble.clip({
	notes: ['c4', ['c4', 'e4', 'g4']],
	pattern: 'xx'
});

scribble.midi(clip);
```

**Comment by walmik** [comment]
@ProgrammingLife Did that work for you?
