### ISSUE TITLE
Add sound engine to play created melody

### ISSUE THREAD

**Issue by surikov** [walmik/scribbletune#63]
Example
https://surikov.github.io/webaudiofont/examples/dynamic.html

It can play created melody in realtime.

**Comment by walmik** [comment]
Hi @surikov this feature is now available in `1.0.0-alpha.1`. You should ideally get it if you do `npm install scribbletune` The [README](https://github.com/walmik/scribbletune/blob/master/README.md) has some info on how to use it and there s a [wiki page](https://github.com/walmik/scribbletune/wiki/Scribbletune-1.0.0-alpha.1-(new-changes-&-goals) I ve also put together for time being.
